### ISSUE TITLE
Make error message more useful

### ISSUE THREAD

**Issue by sarahmaggie33** [bertiniteam/b2#150]
I got the following message while using Pybertini:

```
Traceback (most recent call last):
  File "Path_Tracking_Data_Creator.py", line 84, in <module>
    main(10)
  File "Path_Tracking_Data_Creator.py", line 16, in main
    data_set = create_data(tols, preds)
  File "Path_Tracking_Data_Creator.py", line 27, in create_data
    runtime, successcode = compute_values(t, p, tr, td)
  File "Path_Tracking_Data_Creator.py", line 50, in compute_values
    code = tr.track_path(result=midpath_points[ii], start_time=start_time, end_time=eg_boundar                               y, start_point=td.start_point_mp(ii))
RuntimeError: start point size must match the number of variables in the system to be tracked
```

It would be useful if it printed the number of variables

**Comment by ofloveandhate** [comment]
done.
